services:
  smarthome.deviceapi:
    image: ${DOCKER_REGISTRY-}smarthomedeviceapi
    build:
      context: .
      dockerfile: src/SmartHome.DeviceAPI/Dockerfile
    ports:
      - "5001:8081"
    environment:
      - ASPNETCORE_URLS=http://+:8081
    depends_on:
      - mongo
  mongo:
    container_name: smarthome-mongo-db
    image: mongo
    command: ["mongod", "--port", "27020"]
    ports:
      - "27020:27020"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password